# -*- coding: utf-8 -*-
"""백준1744

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gp0fNWlBmsiGyjQYlWG1tpvPp1dx-C-G
"""

# 수 묶기

N = int(input())
plus_nums = []
minus_nums = []
one_nums = []
for _ in range(N):
    num = int(input())
    if num == 1:
        one_nums.append(num)
    elif num <= 0:
        minus_nums.append(num)
    else:
        plus_nums.append(num)
plus_nums.sort(reverse=True)
minus_nums.sort()

sum = 0
if len(plus_nums) % 2 == 0:
    for i in range(0, len(plus_nums), 2):
        sum += plus_nums[i] * plus_nums[i+1]
else:
    sum += plus_nums[-1]
    for i in range(0, len(plus_nums)-1, 2):
        sum += plus_nums[i] * plus_nums[i+1]

if len(minus_nums) % 2 == 0:
    for i in range(0, len(minus_nums), 2):
        sum += minus_nums[i] * minus_nums[i+1]
else:
    sum += minus_nums[-1]
    for i in range(0, len(minus_nums)-1, 2):
        sum += minus_nums[i] * minus_nums[i+1]
sum += len(one_nums)

print(sum)