# -*- coding: utf-8 -*-
"""백준9625

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jSkHQJRtgJR6fKuFX1ZzYyOGAzc87g5p
"""

# BABBA

K = int(input())
a, b = 1, 0
for i in range(K):
    a, b = b, a+b   
print(a, b, sep=' ')
