# -*- coding: utf-8 -*-
"""백준9935

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qsulfLQiBxPf99ruDgCwlLruBWRrRe4l
"""

# 문자열 폭발

s = input()
bomb = input()

stack = []
for i in s:
    stack.append(i)
    if i == bomb[-1]:
        if ''.join(stack[-len(bomb):]) == bomb:
            for _ in range(len(bomb)):
                stack.pop()
if stack:
    print(''.join(stack))
else:
    print("FRULA")