# -*- coding: utf-8 -*-
"""백준11399

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VNozeFZg3z6bLs6nqKnH5FH0BRHDJOYz
"""

# ATM
N = int(input())
P = map(int, input().split())
sum = 0
total = 0
for i in sorted(P):
    sum += i
    total += sum
print(total)