# -*- coding: utf-8 -*-
"""백준1439

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LmtKkAUHfK6kyTd3_9kyLhRFtDyQhriJ
"""

# 뒤집기

S = input()
cnt0 = 0
cnt1 = 0
for i in range(len(S)-1):
    if (S[i] != S[i+1]) and (S[i] == '0'):
        cnt0 += 1
    elif (S[i] != S[i+1]) and (S[i] == '1'):
        cnt1 += 1
if S[-1] == '0':
    cnt0 += 1
else:
    cnt1 += 1
print(min(cnt0, cnt1))