# -*- coding: utf-8 -*-
"""백준1124

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p52oGDc8lqf-aUSM903v0_Zh_458VuaZ
"""

# 언더프라임

A, B = map(int, input().split())

primes = [False, False] + [True]*(B-1)  # 소수임을 판별하는 리스트
for i in range(2, int(B**(1/2))+1):
    if primes[i]:
        for j in range(2*i, B+1, i):
            primes[j] = False

nums = [0] * (B+1)  # 소인수의 개수를 담는 리스트

for i in range(2, B+1):
    if primes[i]:
        nums[i] = 1
    for j in range(2, B//i+1):
        if primes[j]:
            nums[i*j] = nums[i] + 1


cnt = 0
for i in range(A, B+1):
    if primes[nums[i]]:
        cnt += 1
print(cnt)