# -*- coding: utf-8 -*-
"""백준10819

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ECgnei-RJcRyO2H87RlkKin8iVKa2bWf
"""

# 차이를 최대로
from itertools import permutations

N = int(input())
nums = list(map(int, input().split()))
max = 0
for i in permutations(nums):
    sum = 0
    for j in range(len(i)-1):
        sum += abs(i[j]-i[j+1])
    if max < sum:
        max = sum
print(max)