# -*- coding: utf-8 -*-
"""백준23841

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l9j77HbnC0jC9SboIKkFOdEGEUUzF_TY
"""

# 데칼코마니

N, M = map(int, input().split())
for _ in range(N):
    picture = input()
    for i in range(len(picture)):
        if picture[i] != '.':
            print(picture[i], end='')
        elif picture[-i-1] != '.':
            print(picture[-i-1], end='')
        else:
            print('.', end='')
    print()