# -*- coding: utf-8 -*-
"""백준10996

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i0xJvHSwIMMEM3x26MiVFJba2zFn4zdM
"""

# 별 찍기 - 21
N = int(input())

for i in range(2*N):
    for j in range(1,N+1):
        if (i % 2) + (j % 2) == 1:
            print("*", end='')
        else:
            print(" ", end='')
    print()