# -*- coding: utf-8 -*-
"""백준1026

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1drHho5RM-sJWnW7cT_3mJzs1gQp0ZLJL
"""

# 보물
N = int(input())
A = list(map(int, input().split()))
B = list(map(int, input().split()))
sorted_A = sorted(A, reverse=True)
sorted_B = sorted(B)
sum = 0

for i in range(N):
    sum += sorted_A[i] * sorted_B[i]
print(sum)