# -*- coding: utf-8 -*-
"""백준11047

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aMclxcuP3exTCN9wIX-n8MaABrfhZsrS
"""

# 동전 0

N, K = map(int, input().split())
coins = []
for _ in range(N):
    coin = int(input())
    coins.append(coin)
coins.reverse()

cnt = 0
for i in coins:
    cnt += K // i
    K %= i
print(cnt)