# -*- coding: utf-8 -*-
"""백준17219

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ALwNkqzyjwFoWmAtlIvXAEjMEDQHviU0
"""

# 비밀번호 찾기
import sys
input = sys.stdin.readline

N, M = map(int, input().split())
passwords = {}
for _ in range(N):
    site, password = input().split()
    passwords[site] = password
for _ in range(M):
    site = input().rstrip() # 개행문자 (\n)까지 받기 때문에 rstrip()사용
    print(passwords[site])
