# -*- coding: utf-8 -*-
"""백준1676

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14qkZI7Oq8WY-ezJBa47zet-4sGhxYr3s
"""

# 팩토리얼 0의 개수

N = int(input())
print(N//5 + N//25 + N//125) 
