# -*- coding: utf-8 -*-
"""백준1931

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UOEmVYB35yrC5WldCofv60O2WLd6GwYm
"""

# 회의실 배정

meeting = []
N = int(input())
for _ in range(N):
    start, end = map(int, input().split())
    meeting.append([start, end])
meeting.sort(key=lambda x: x[0])
meeting.sort(key=lambda x: x[1])

start, end = meeting[0][0], meeting[0][1]
count = 1
for i in range(1, len(meeting)):
    if end > meeting[i][0]:
        continue
    else:
        end = meeting[i][1]
        count += 1
print(count)