# -*- coding: utf-8 -*-
"""백준2775

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IkL_6Eat95kedyL8vHewnQOk_zBK9CIC
"""

T = int(input())
for _ in range(T):
    k = int(input())
    n = int(input())
    floor0 = [x for x in range(1, n+1)]
    for j in range(k):
        for i in range(1,n):
            floor0[i] += floor0[i-1]
    print(floor0[-1])