# -*- coding: utf-8 -*-
"""백준2559

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j9fK6-6sfsPPRLtCh_7Rx3iqAQ0eGwvc
"""

# 수열 

N, k = map(int, input().split())
temp = list(map(int, input().split()))

total = sum(temp[:k])
best = total
for i in range(len(temp)-k):
    total -= temp[i]
    total += temp[k+i]
    if total > best:
        best = total
print(best)
